version: '3'

services:
  app:
    env_file: ./.env.docker
    build: .
    ports: 
      - 3333:3333
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - 5432:5432